import React from 'react';
import {
  Sparkles,
  Cpu,
  X,
  ShieldCheck,
  Clock,
  Building2,
  AlertTriangle,
  FileCheck2,
  CheckCircle2,
  Info
} from 'lucide-react';
import Button from '../Button';

/**
 * AITriageDetailsDrawer Component
 * Displays automated diagnostic and categorization triage results generated by the Civic AI Intelligence Engine.
 * Explicitly distinguishes automated AI predictions from ground-truth verified records.
 */
export const AITriageDetailsDrawer = ({
  isOpen,
  onClose,
  complaint
}) => {
  if (!isOpen || !complaint) return null;

  const ai = complaint.aiAnalysis || {
    issue: complaint.issueType || 'civic_hazard',
    severity: complaint.severity?.toLowerCase() || 'medium',
    priority: complaint.priority?.toLowerCase() || 'medium',
    department: complaint.department,
    sla_hours: 48,
    action: 'inspect_and_triage',
    confidence: 0.92,
    reason: 'Automated civic natural language classification based on report description.'
  };

  const confidencePercent = Math.round((ai.confidence || 0.90) * 100);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="ai-drawer-title"
      className="fixed inset-0 z-50 overflow-hidden bg-slate-900/50 backdrop-blur-xs flex justify-end"
    >
      <div className="w-full max-w-md bg-white h-full shadow-2xl flex flex-col border-l border-slate-200 animate-in slide-in-from-right duration-200">
        {/* Drawer Header */}
        <div className="px-6 py-5 border-b border-slate-100 flex items-center justify-between bg-slate-50/70">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-indigo-50 border border-indigo-200 text-indigo-700 flex items-center justify-center">
              <Cpu className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-1.5">
                <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-700 bg-indigo-100/60 px-2 py-0.5 rounded">
                  Civic AI Engine
                </span>
                <span className="text-xs text-slate-400 font-mono">{complaint.id}</span>
              </div>
              <h2 id="ai-drawer-title" className="text-sm font-bold text-slate-900 mt-0.5">
                Automated Triage Analysis
              </h2>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-100 transition-colors"
            aria-label="Close AI Drawer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Drawer Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 text-xs">
          {/* Important AI Disclaimer Banner */}
          <div className="p-3.5 bg-indigo-50/60 border border-indigo-200/80 rounded-xl space-y-1.5">
            <div className="flex items-center gap-1.5 font-bold text-indigo-950">
              <Sparkles className="w-3.5 h-3.5 text-indigo-600 shrink-0" />
              <span>Diagnostic Assessment (Advisory Only)</span>
            </div>
            <p className="text-[11px] text-indigo-900 leading-relaxed">
              This triage record is automatically generated by the Gemini Civic Intelligence pipeline. Departmental authority confirmation is required prior to financial or equipment mobilization.
            </p>
          </div>

          {/* Core AI Classification Metrics */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              Classification & Urgency Signals
            </h3>

            <div className="grid grid-cols-2 gap-3">
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="text-[11px] text-slate-500 font-medium">Issue Classification</span>
                <p className="text-sm font-bold text-slate-900 capitalize font-mono">
                  {ai.issue.replace(/_/g, ' ')}
                </p>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="text-[11px] text-slate-500 font-medium">Model Confidence</span>
                <div className="flex items-center gap-1.5">
                  <span className="text-sm font-bold text-indigo-700 font-mono">
                    {confidencePercent}%
                  </span>
                  <span className="text-[10px] text-slate-400">({ai.confidence})</span>
                </div>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="text-[11px] text-slate-500 font-medium">Assessed Severity</span>
                <p className="text-xs font-bold text-slate-800 capitalize">
                  {ai.severity}
                </p>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-1">
                <span className="text-[11px] text-slate-500 font-medium">Triage Priority</span>
                <p className="text-xs font-bold text-slate-800 capitalize">
                  {ai.priority}
                </p>
              </div>
            </div>
          </div>

          {/* Department Routing & Recommended SLA */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              Departmental Routing & SLA
            </h3>

            <div className="p-4 rounded-xl border border-slate-200 space-y-3 bg-white shadow-xs">
              <div className="flex items-start gap-3">
                <Building2 className="w-4 h-4 text-civic-700 mt-0.5 shrink-0" />
                <div className="space-y-0.5">
                  <span className="text-[11px] text-slate-500 font-medium">Suggested Department</span>
                  <p className="text-xs font-bold text-slate-900">
                    {ai.department}
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 pt-2 border-t border-slate-100">
                <Clock className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
                <div className="space-y-0.5">
                  <span className="text-[11px] text-slate-500 font-medium">Recommended SLA Limit</span>
                  <p className="text-xs font-bold text-slate-900">
                    {ai.sla_hours} Hours Response Window
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3 pt-2 border-t border-slate-100">
                <FileCheck2 className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                <div className="space-y-0.5">
                  <span className="text-[11px] text-slate-500 font-medium">Suggested Operational Action</span>
                  <p className="text-xs font-bold text-slate-800 font-mono">
                    {ai.action}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* AI Rationale / Reasoning */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              Triage Rationale & Evidence Context
            </h3>
            <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-700 leading-relaxed">
              <p className="text-xs">{ai.reason}</p>
            </div>
          </div>

          {/* Raw Structure Preview (for technical inspection) */}
          <div className="space-y-2 pt-2 border-t border-slate-100">
            <div className="flex items-center justify-between text-[11px] text-slate-400">
              <span>Standardized Schema Output</span>
              <span>JSON Payload</span>
            </div>
            <pre className="p-3 bg-slate-900 text-emerald-400 rounded-xl text-[11px] font-mono overflow-x-auto">
              {JSON.stringify(
                {
                  issue: ai.issue,
                  severity: ai.severity,
                  priority: ai.priority,
                  department: ai.department,
                  sla_hours: ai.sla_hours,
                  action: ai.action,
                  confidence: ai.confidence
                },
                null,
                2
              )}
            </pre>
          </div>
        </div>

        {/* Drawer Footer */}
        <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-end">
          <Button size="sm" variant="secondary" onClick={onClose}>
            Close Analysis
          </Button>
        </div>
      </div>
    </div>
  );
};

export default AITriageDetailsDrawer;
